### ISSUE TITLE
Change in generator API

### ISSUE THREAD

**Issue by necolas** [suitcss/generator-suit#4]
Will need to rewrite things to deal with the API change in `yeoman-generator` 0.16 - http://yeoman.io/blog/cleanup.html

**Comment by giuseppeg** [comment]
At this point seems like that the generator doesn't work anymore.

```bash
giuseppe$ yo suit test
fs.js:568
  function strWrapper(err, written) {
                ^
Error: ENOENT, no such file or directory '/Users/giuseppe/.node/lib/node_modules/generator-suit/lib/templates/app/gitignore'
    at Error (native)
    at Object.fs.openSync (fs.js:502:18)
    at Object.fs.readFileSync (fs.js:354:15)
    at Generator.copy (/Users/giuseppe/.node/lib/node_modules/generator-suit/node_modules/yeoman-generator/lib/actions/actions.js:102:13)
    at Generator.projectFiles (/Users/giuseppe/.node/lib/node_modules/generator-suit/lib/generators/app/index.js:44:8)
    at /Users/giuseppe/.node/lib/node_modules/generator-suit/node_modules/yeoman-generator/lib/base.js:290:20
    at /Users/giuseppe/.node/lib/node_modules/generator-suit/node_modules/yeoman-generator/node_modules/async/lib/async.js:551:21
    at /Users/giuseppe/.node/lib/node_modules/generator-suit/node_modules/yeoman-generator/node_modules/async/lib/async.js:227:13
    at iterate (/Users/giuseppe/.node/lib/node_modules/generator-suit/node_modules/yeoman-generator/node_modules/async/lib/async.js:134:13)
    at async.eachSeries (/Users/giuseppe/.node/lib/node_modules/generator-suit/node_modules/yeoman-generator/node_modules/async/lib/async.js:150:9)
```

Are you planning to release a new version anytime soon?
If not I can help with the rewrite.
